services:
  mongodb:
    image: 'mongo:7.0'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: 'postgres:16.0'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jaeger:
    image: 'jaegertracing/all-in-one:1.57.0'
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
      COLLECTOR_ZIPKIN_HOST_PORT: ':9411'
    ports:
      - '16686:16686'
      - '4318:4318'
      - '9411:9411'

volumes:
  mongodb-data:
  postgres-data:
