spring:
  application:
    name: todo

  mongodb:
    uri: ${MONGODB_URI:mongodb://127.0.0.1:27017/todo}
    uuid-representation: standard

logging:
  structured:
    format:
      console: ecs
  level:
    dev.souto.todo: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    group:
      liveness:
        include: livenessState
      readiness:
        include: readinessState,mongo

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
